### ISSUE TITLE
Build on macOS Mojave 10.14.1 cmake configure faild! Can someone help me?

### ISSUE THREAD

**Issue by 2908755265** [andlabs/libui#460] opened 2019-03-26 07:19 UTC
I am not good at cmake. But this project need it, so I installed it just now.

cmake version 3.14.0 

When I configure, cmake output this :

Determining if the CXX compiler works failed with the following output:
Change Dir: /Users/wangqiang/phpui/libui/out/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_8f0d2/fast 
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_8f0d2.dir/build.make CMakeFiles/cmTC_8f0d2.dir/build
Building CXX object CMakeFiles/cmTC_8f0d2.dir/testCXXCompiler.cxx.o
/Library/Developer/CommandLineTools/usr/bin/c++    -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.8   -o CMakeFiles/cmTC_8f0d2.dir/testCXXCompiler.cxx.o -c /Users/wangqiang/phpui/libui/out/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
1 warning generated.
Linking CXX executable cmTC_8f0d2
/Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8f0d2.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/c++    -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.8 -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_8f0d2.dir/testCXXCompiler.cxx.o  -o cmTC_8f0d2 
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_8f0d2] Error 1
make: *** [cmTC_8f0d2/fast] Error 2

**Comment by andlabs** [comment] 2019-03-26 12:40
Duplicate of #422; update your cmake.

**Comment by mischnic** [comment] 2019-03-26 17:51
I still have this error even with the newest cmake. 
Setting this seems to help:
```sh
export SDKROOT='/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk'
```

**Comment by andlabs** [comment] 2019-03-26 18:33
Try `xcode-select --install` then? I'm not sure what causes SDKROOT to be set or not...

**Comment by mischnic** [comment] 2019-03-26 19:25
> Try xcode-select --install then

That does nothing.

**Comment by kaka012** [comment] 2019-03-30 20:09
For me exporting SDKROOT makes no difference.
The issue seems to be that Apple's `clang++` passes `-lc++` to `ld` (Apple's linker) if the MacOS target is 10.9 or higher, but passes `-lstdc++` to ld if the MacOS target is 10.8 or lower.
The current SDK (`MacOSX10.14.sdk`) doesn't have `libstdc++.tbd`, but only `libc++.tbd` (Found in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc++.tbd`).
The old SDK (`MacOSX10.13.sdk`) actually had `libstdc++.tbd` ([source](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.13.sdk/usr/lib/libstdc%2B%2B.6.0.9.tbd)).
During CMake's compiler sanity check the `CMAKE_CXX_FLAGS` are reset, but the `CMAKE_OSX_DEPLOYMENT_TARGET` is kept, which is why the internal try_compile fails and we can't inject `-stdlib=libc++` into the compilation check to make it pass.
The easiest solution would be to drop support for MacOS 10.8 and lower:
```diff
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -19,1 +19,1 @@
-set(CMAKE_OSX_DEPLOYMENT_TARGET "10.8" CACHE STRING "" FORCE)
+set(CMAKE_OSX_DEPLOYMENT_TARGET "10.9" CACHE STRING "" FORCE)
```
Doing this is quite reasonable, since Apple is no longer supplying security updates for MacOS 10.8 (only for 10.9 or higher; [source](https://support.apple.com/en-us/HT201222)).

**Comment by andlabs** [comment] 2019-03-30 21:35
I am almost done replacing cmake, so this problem should go away soon. But the Determining if the CXX compiler works step is a cmake internal step, not one that libui has any control over, and if cmake isn't handling a project setting like the deployment target properly, that's a bug in cmake.

**Comment by kaka012** [comment] 2019-03-30 22:31
Apparently I didn't read the [try_compile docs](https://cmake.org/cmake/help/latest/command/try_compile.html#id4) closely enough. [CMP0056](https://cmake.org/cmake/help/latest/policy/CMP0056.html) can be used to propagate `-stdlib=libc++` as part of the `CMAKE_EXE_LINKER_FLAGS` into the `try_compile` environment. This avoids dropping MacOS 10.8 but has to drop support for CMake <3.2.0 on MacOS to work.

**Comment by andlabs** [comment] 2019-03-30 23:49
This policy was introduced in CMake version 3.2. Unlike most policies, CMake version 3.14.1 does not warn by default when this policy is not set and simply uses OLD behavior. See documentation of the CMAKE_POLICY_WARNING_CMP0056 variable to control the warning.

incredible

**Comment by andlabs** [comment] 2019-04-08 04:25
The switch has happened; closing.

**Closed by andlabs** 2019-04-08 04:25 UTC
Labels: cmake dumbness
