### ISSUE TITLE
Leaked Memory

### ISSUE THREAD

**Issue by HalosGhost** [andlabs/libui#56] opened 2016-05-23 22:04 UTC
It looks like, even on some of the simplest examples, libui inherently leaks around 1.5MiB of memory. See the following:

```c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ui.h>

static uiWindow * w;

static signed
shouldQuit (void * data) {

    (void )data;
    uiControlDestroy(uiControl(w));
    return 1;
}

static signed
onClosing (uiWindow * win, void * data) {

    (void )win;
    shouldQuit(data);
    uiQuit();
    return 0;
}

signed
main (void) {

    uiInitOptions o;
    memset(&o, 0, sizeof(uiInitOptions));

    const char * err = uiInit(&o);
    if ( err ) {
        fprintf(stderr, "libui test: error initializing UI: %s\n", err);
        uiFreeInitError(err);
        return EXIT_FAILURE;
    }

    w = uiNewWindow("Hello, World!", 800, 600, 1);
    uiWindowOnClosing(w, onClosing, NULL);

    uiLabel * l = uiNewLabel("Hello, World!");
    uiWindowSetChild(w, uiControl(l));

    uiControlShow(uiControl(w));
    uiMain();
    uiUninit();
    return EXIT_FAILURE;
}
```

Given the above code snippet, which only spawns a window with a text label, I get the following output from ``valgrind``:

```console
$ valgrind ./a.out
==17778== Memcheck, a memory error detector
==17778== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==17778== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==17778== Command: ./a.out
==17778==
==17778== HEAP SUMMARY:
==17778==     in use at exit: 1,574,098 bytes in 17,720 blocks
==17778==   total heap usage: 165,359 allocs, 147,639 frees, 10,457,187 bytes allocated
==17778==
==17778== LEAK SUMMARY:
==17778==    definitely lost: 1,280 bytes in 2 blocks
==17778==    indirectly lost: 6,629 bytes in 272 blocks
==17778==      possibly lost: 3,428 bytes in 45 blocks
==17778==    still reachable: 1,493,033 bytes in 16,843 blocks
==17778==                       of which reachable via heuristic:
==17778==                         length64           : 3,320 bytes in 59 blocks
==17778==                         newarray           : 2,032 bytes in 47 blocks
==17778==         suppressed: 0 bytes in 0 blocks
==17778== Rerun with --leak-check=full to see details of leaked memory
==17778==
==17778== For counts of detected and suppressed errors, rerun with: -v
==17778== ERROR SUMMARY: 43 errors from 24 contexts (suppressed: 0 from 0)
```

**Comment by andlabs** [comment] 2016-05-23 22:17
Is there a way we can dump the contents of that leaked memory? Does valgrind not know where it is? I've never used valgrind beyond basic logging.

**Comment by Extrawurst** [comment] 2016-05-23 22:18
`Rerun with --leak-check=full to see details of leaked memory`

**Comment by HalosGhost** [comment] 2016-05-23 22:28
You can find a link to the full output from ``--leak-check=full`` [here](https://ptpb.pw/HlHl). I did not include it originally because it is _a lot_.

**Comment by andlabs** [comment] 2016-05-23 22:54
If the GTK+ equivalent I pasted also exhibits the same leaks, that's the source of them. I know there ar ea few objects that I don't know if I should be freeing them or not, but I don't think any are used by the program you posted...

**Comment by HalosGhost** [comment] 2016-05-23 23:51
Using your snippet, and the following compilation, I get the given ``valgrind`` output:

```console
$ clang $(pkg-config --libs --cflags gtk+-3.0) <yoursnippetinafile>.c
$ valgrind ./a.out
==19774== Memcheck, a memory error detector
==19774== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==19774== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==19774== Command: ./a.out
==19774==
==19774==
==19774== HEAP SUMMARY:
==19774==     in use at exit: 1,392,159 bytes in 14,646 blocks
==19774==   total heap usage: 160,221 allocs, 145,575 frees, 9,423,544 bytes allocated
==19774==
==19774== LEAK SUMMARY:
==19774==    definitely lost: 0 bytes in 0 blocks
==19774==    indirectly lost: 0 bytes in 0 blocks
==19774==      possibly lost: 3,328 bytes in 44 blocks
==19774==    still reachable: 1,320,543 bytes in 14,053 blocks
==19774==                       of which reachable via heuristic:
==19774==                         length64           : 3,280 bytes in 58 blocks
==19774==                         newarray           : 2,000 bytes in 45 blocks
==19774==         suppressed: 0 bytes in 0 blocks
==19774== Rerun with --leak-check=full to see details of leaked memory
==19774==
==19774== For counts of detected and suppressed errors, rerun with: -v
==19774== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

That suggests this is not an underlying issue with gtk+.

**Comment by andlabs** [comment] 2016-05-23 23:58
All right. The only question then is what those blocks are... (I had machinery in `*/alloc.*` for preventing this sort of thing; I guess it's not perfect =P )

**Comment by HalosGhost** [comment] 2016-05-24 19:02
I will try adding ``-fsanitize=memory`` to figure out what exactly went wrong.

**Comment by andlabs** [comment] 2016-05-24 19:37
Probably. I don't use fontconfig directly either; it might still be caused by GTK+...?

**Comment by HalosGhost** [comment] 2016-05-24 20:30
Indeed, that test program does show the exact same 7909 bytes leaked directly and indirectly.

It seems that that would confirm the issue is in GTK itself!

**Comment by andlabs** [comment] 2016-05-25 00:50
So does this mean the leaks at the beginning were not in libui? Either way, good to know.

I'm sure if you dig deep enough you'll find a leak in libui itself, possibly annotated with a "TODO do I release this?" =P

**Comment by HalosGhost** [comment] 2016-05-25 01:00
Well, it depends. It seems the leaked memory is coming from gtk, not libui itself. But I'm surprised to see gtk have such memory leaks on such basic things. Is there a chance that some cleanup routines should be being performed and are not?

**Comment by andlabs** [comment] 2016-05-25 01:07
At this point you would have to ask them because I wouldn't know. It could instead be a bug in pango or fontconfig as well...

**Comment by HalosGhost** [comment] 2016-05-25 01:09
Haha. All right, I will take a bit more of a look into it; if it seems like it is a cleanup routine that should be used by libui, then I will post the related information here; if not, I will close the issue and look into opening a issue on the correct issue tracker.

**Comment by jfcg** [comment] 2016-05-25 14:10
Glib object system is a weird one, valgrind-like tools occasionally have trouble debugging it. That probably is not a real leak in gtk. That is just the way gtk/glib works.

**Comment by HalosGhost** [comment] 2016-05-25 14:18
@jfcg, this is not just Valgrind, it is also clang's LSan. I am only focused on the 7909 bytes that the LSan can prove have been leaked.

**Comment by andlabs** [comment] 2016-06-06 02:08
I'm going to close this for now. Please feel free to report any future leaks that do seem to come from libui itself. As I have said, there's likely some obscure part that I've missed :)

**Closed by andlabs** 2016-06-06 02:08 UTC
