### ISSUE TITLE
Bug: sample application hangs on Windows 7

### ISSUE THREAD

**Issue by SevenBits** [andlabs/libui#92] opened 2016-06-01 23:55 UTC
Unsure if this is a bug in libui or in your sample code.

Steps to reproduce:

1. Download the [binaries of the latest release](https://github.com/andlabs/libui/releases/download/alpha3/alpha3.tar.gz).

1. Run the control gallery sample application (x86 or x64 does not matter, neither does static vs shared build configuration).

1. Enter a value into the spinbox and press Enter.

The application then crashes.

**Comment by andlabs** [comment] 2016-06-02 00:28
Duplicate of #55

**Closed by andlabs** 2016-06-02 00:28 UTC
