### ISSUE TITLE
Release build fails on Visual Studio 2015

### ISSUE THREAD

**Issue by rdeterre** [andlabs/libui#262] opened 2017-04-11 14:28 UTC
Running a release build of libui from tag `alpha3.1` fails with error `cl : Command line error D8016: '/O2' and '/RTCu' command-line options are incompatible`.

This seems to be fixed by removing the runtime check flags from `_COMMON_CFLAGS` in `CMakeLists.txt`.

Full compilation log is here: https://gist.github.com/rdeterre/d21b4c4712766171dac5c11d585a0ab2

**Comment by andlabs** [comment] 2017-04-12 04:15
Duplicate of #261.

**Closed by andlabs** 2017-04-12 04:15 UTC
