### ISSUE TITLE
Is libui dead?

### ISSUE THREAD

**Issue by steelbrain** [andlabs/libui#274] opened 2017-07-16 17:21 UTC
I noticed that the master branch hasn't been updated since Dec 2, 2016. Does it mean that libui is dead / no longer maintained or did you achieve the state of the API that no longer needs any updates?

I want to use libui in one of my projects but am concerned because neither libui nor some of it's bindings to other languages have been updated since December of last year.

**Comment by marcotrosi** [comment] 2017-07-16 17:59
I hope not, because libui could be my only solution. And Gunnar just released an update of his Lua bindings https://hg.tset.de/public/lui/rev/7e6d577f160d

**Comment by andlabs** [comment] 2017-07-16 18:49
I am working off master.

**Comment by lukechilds** [comment] 2017-07-29 10:05
@andlabs Have you considered accepting donations through a platform such as [Open Collective.com](https://opencollective.com)?

I think there is high demand for a library such as libui to exist, if it gained some traction maybe that could allow you to dedicate more time on this.

**Comment by marcotrosi** [comment] 2017-08-01 13:52
@lukechilds is also have not found any other library like libui. It has the potential to be something great maybe even a de-facto standard. If you want something big, nowadays you would chose Qt I guess, but if you want something small and simple then libui is probably the one. Am I wrong?

**Comment by dertuxmalwieder** [comment] 2017-08-07 00:55
There is IUP which has a lovely support, so there *would* be an alternative for C GUIs. However, I sure do hope that libui won't die soon. 

I suppose the problem is not money but time, so it would probably make more sense to contribute code instead of collecting donations. 

@andlabs Is there any current work we could help with?

**Comment by marcotrosi** [comment] 2017-08-07 04:58
As far as I know IUP does not support macOS with native Cocoa but GTK instead. But libui does that, doesn't it?

**Comment by dertuxmalwieder** [comment] 2017-08-07 08:53
That is correct, although macOS support is on their [ToDo list](http://webserver2.tecgraf.puc-rio.br/iup/en/to_do.html).

**Comment by andlabs** [comment] 2017-08-13 03:48
Admittedly I've been lazy and with low motivation recently. I'll try to continue tomorrow or sometime in the next few days or something... I'm almost done with the new text drawing stuff, at least.

**Comment by lukechilds** [comment] 2017-08-13 08:50
> Admittedly I've been lazy

@andlabs Always remember, with OSS you don't owe anyone anything.

**Comment by eXpl0it3r** [comment] 2017-10-07 17:45
I'd recommend to find someone or a couple of others to help you out. Working in a team doesn't always make things easier, but it may allow to spread the work. For example just taking someone knowledgeable of the lib to clean up the existing PR list or go through and checking the various issues.

Keep it up!

**Comment by cody271** [comment] 2017-10-07 20:50
@andlabs I'm still here to help!

**Comment by andlabs** [comment] 2017-10-08 00:29
Right. I'll get to the PRs once I finish the utflib-and-attrstr branch, because it's going to be a significant, backwards-incompatible API change.

**Comment by jspraul** [comment] 2017-11-03 12:19
@andlabs 

Based on the number of outstanding pull requests I highly encourage delegating management/merge responsibilities to someone with a proven track record so that you can focus on the the development aspects that most interest you.

**Comment by helmishariff** [comment] 2017-12-29 06:18
i just found this library. Any update with this library?

**Comment by tom-corwin** [comment] 2018-01-16 03:10
@andlabs Is there any timeframe as to when the `utflib-and-attrstr` branch will be merged into master? (And then, another release?)

**Comment by andlabs** [comment] 2018-01-16 06:04
No. I work for a new company now, and I need copyright clearance from them before I can continue writing code (unless I want to assign copyright for the new code to them). Sorry. Of course, once I do get that, I will push out the "alpha 3.5" patch idea (quick push of #202) and continue working on `utflib-and-attrstr`, which is presently having a final cleanup phase of its current feature set (which will be sufficient for a merge, but not ideal, but I want to get other stuff done too).

**Comment by dertuxmalwieder** [comment] 2018-01-16 10:00
Enjoy your new job!

**Comment by andlabs** [comment] 2018-02-17 17:39
Clearance obtained. Let's get busy again.

**Closed by andlabs** 2018-02-17 17:39 UTC

**Comment by PaluMacil** [comment] 2018-02-17 18:07
Thanks for the update on the copyright clearance!! 👍 It's fantastic news!

**Comment by ridams** [comment] 2018-03-23 11:04
Is there a widget for like  GtkTreeView both for treestore and liststore?

**Comment by andlabs** [comment] 2018-03-23 12:16
It is WIP. Anyway, this particular topic is resolved.
