### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by undeadindustries** [andlabs/libui#393] opened 2018-06-18 00:19 UTC
Hi there. I just remember a few months ago you were redesigning the table partof libui. Just wondering if you made any progress?

**Comment by bcampbell** [comment] 2018-06-18 01:17
@andlabs is crankng out new table code at a furious rate right now, in the table branch. #310 is the issue covering all the table work.

**Comment by andlabs** [comment] 2018-06-18 01:59
Duplicate of #310

**Closed by andlabs** 2018-06-18 01:59 UTC
