### ISSUE TITLE
use of double underscore and underscore lettre prefix is reserved!

### ISSUE THREAD

**Issue by informatimago** [andlabs/libui#362] opened 2018-05-08 15:22 UTC
__LIBUI_UI_H__ and _UI_EXTERN are identifiers that are reserved for the compiler. User programs must not use such identifiers! cf. the ANSI C standards, or http://c-faq.com/decl/namespace.html

UI_EXTERN or LIBUI_UI_H are perfectly good replacements.
(and similarly for all the others, such as _UI_ENUM, etc).

**Comment by parro-it** [comment] 2018-05-08 15:25
Duplicate of https://github.com/andlabs/libui/issues/23

**Comment by informatimago** [comment] 2018-05-08 15:25
Oops, sorry.

**Comment by andlabs** [comment] 2018-05-08 15:46
Closed  as duplicate

**Closed as completed** 2018-05-08 15:45 UTC
