### ISSUE TITLE
Heavy flickering and slow tab changing on Windows 10

### ISSUE THREAD

**Issue by qoh** [andlabs/libui#243] opened 2016-12-12 09:34 UTC
http://i.imgur.com/wqrIt4c.gifv

32-bit build from VS 2015, running on a i5-4200M and Intel HD Graphics 4600
Is this known behavior? Why does this happen?

**Comment by andlabs** [comment] 2016-12-12 12:07
Duplicate of https://github.com/andlabs/ui/issues/184

**Comment by andlabs** [comment] 2016-12-12 12:09
On second thought I'll keep this open in the meantime.

**Comment by zhaozg** [comment] 2018-01-26 12:42
https://github.com/andlabs/ui/issues/184#issuecomment-242686886 works for me fine.

**Comment by andlabs** [comment] 2018-01-26 15:18
Yes; I did not apply that fix specifically because it makes things look ugly. The proper fix would require yet another major upheaval as to how uiControl and uiWindowsControl work/.

**Comment by andlabs** [comment] 2018-03-23 21:44
Replaced with #311.

**Closed by andlabs** 2018-03-23 21:44 UTC
