### ISSUE TITLE
Context menu control

### ISSUE THREAD

**Issue by endoffile78** [andlabs/libui#352] opened 2018-04-28 20:31 UTC
A control where when the user right clicks on something a menu will popup. It could be very similiar to the dropdown api.

**Comment by mischnic** [comment] 2018-04-28 20:43
Are you thinking of a specific *control* (how should that look like) or the possibility to add a context menu to every control.

**Comment by endoffile78** [comment] 2018-04-28 20:54
I was thinking something like [https://developer.gnome.org/gtkmm-tutorial/stable/figures/treeview_popup.png.en](this). Whenever you right click on any control you could get a context menu.

**Comment by andlabs** [comment] 2018-04-29 00:02
Duplicate of #321 (though I forgot to list right-click menus there)

Not sure about *any* control, though.

**Closed by andlabs** 2018-04-29 00:02 UTC
