### ISSUE TITLE
controlgallery "Some data was leaked"

### ISSUE THREAD

**Issue by kainjow** [andlabs/libui#53] opened 2016-05-23 20:02 UTC
On 10.11.5, when I run the controlgallery example and then close it via the window to quit, I get this:

> $ ./out/controlgallery 
2016-05-23 13:01:05.503 controlgallery[39763:203248] [libui] darwin/alloc.m:45:uninitAlloc() You have a bug: Some data was leaked; either you left a uiControl lying around or there's a bug in libui itself. Leaked data:
0x7fa60370cc40 struct mapTable
Illegal instruction: 4

**Comment by andlabs** [comment] 2016-05-23 20:21
Duplicate of #14

**Closed by andlabs** 2016-05-23 20:21 UTC
