### ISSUE TITLE
CMake does not configure

### ISSUE THREAD

**Issue by IngwiePhoenix** [andlabs/libui#457] opened 2019-02-12 20:47 UTC
So, there are two major problems:

1. You are apparently pointing explicitly to a `libstdc++`
2. You are trying to link against that library - and it fails.

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/G/l/out $ cmake ..
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- broken
CMake Error at /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/Ingwie/Work/Git/libui/out/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/local/bin/gmake" "cmTC_a0bfd/fast"
    /Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_a0bfd.dir/build.make CMakeFiles/cmTC_a0bfd.dir/build
    Building CXX object CMakeFiles/cmTC_a0bfd.dir/testCXXCompiler.cxx.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.8   -o CMakeFiles/cmTC_a0bfd.dir/testCXXCompiler.cxx.o -c /Users/Ingwie/Work/Git/libui/out/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    1 warning generated.
    Linking CXX executable cmTC_a0bfd
    /usr/local/Cellar/cmake/3.13.4/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a0bfd.dir/link.txt --verbose=1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.8 -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_a0bfd.dir/testCXXCompiler.cxx.o  -o cmTC_a0bfd 
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_a0bfd] Error 1
    make: *** [cmTC_a0bfd/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:35 (project)


-- Configuring incomplete, errors occurred!
See also "/Users/Ingwie/Work/Git/libui/out/CMakeFiles/CMakeOutput.log".
See also "/Users/Ingwie/Work/Git/libui/out/CMakeFiles/CMakeError.log".
Ingwie@Ingwies-Macbook-Pro.local ~/W/G/l/out $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D42
```

I am not much of a CMake guy, but what I would suggest to try:
- Use the suggested flag given by Clang
- Or maybe don't try to link against the C++ runtime at all, let the compiler do it, maybe.

Hope it helps :)

**Comment by andlabs** [comment] 2019-02-13 02:05
This issue has already been reported, and is a bug in CMake, not in libui. You'll need to pester them at https://gitlab.kitware.com/cmake/cmake/issues/18396.

Duplicate of #422

**Closed by andlabs** 2019-02-13 02:05 UTC
