### ISSUE TITLE
How to retrieve date/time from an uiDateTimePicker instance?

### ISSUE THREAD

**Issue by LumingYin** [andlabs/libui#360] opened 2018-05-04 17:36 UTC
It is possible to get text out of uiEntry instances with uiEntryText, but how would I be able retrieve date/time from an uiDateTimePicker instance?

**Comment by parro-it** [comment] 2018-05-04 17:41
It's not implemented yet. See this PR: #297

**Comment by andlabs** [comment] 2018-05-04 17:42
Duplicate of #309

**Comment by andlabs** [comment] 2018-05-04 17:42
probably the wrong duplicate issue but meh

**Closed by andlabs** 2018-05-04 17:42 UTC

**Comment by parro-it** [comment] 2018-05-04 17:43
Hey is this a new GH feature? Awesome!

![image](https://user-images.githubusercontent.com/11197111/39642912-65df1516-4fd3-11e8-82ee-2fb364c4d86f.png)
