### ISSUE TITLE
Entering a value in spinboxes crashes the program

### ISSUE THREAD

**Issue by joa-quim** [andlabs/libui#77] opened 2016-05-28 15:09 UTC
Just build the examples/histogram and make an Enter in any of the spinboxes. Program crashes right away.

**Comment by andlabs** [comment] 2016-05-28 15:17
What OS?

**Comment by joa-quim** [comment] 2016-05-28 16:18
Sorry forgot that. Windows

**Comment by andlabs** [comment] 2016-05-28 16:21
Duplicate of #55. Spinboxes and entries use the same edit controls that have this issue. Now I just wish github had issue prioritizing, since that'll have to become a serious issue since a lot of people are getting it...

**Closed by andlabs** 2016-05-28 16:21 UTC
