### ISSUE TITLE
A uiStep would be nice

### ISSUE THREAD

**Issue by Someguynamedpie** [andlabs/libui#37] opened 2016-05-20 21:55 UTC
As opposed to using uiMain, a function we can call that would poll events, etc, would be nice so we can have multiple things on the main thread as well.

**Comment by andlabs** [comment] 2016-05-20 22:17
Duplicate of #21.

**Closed by andlabs** 2016-05-20 22:17 UTC

**Comment by andlabs** [comment] 2016-05-25 03:28
Done. See #21 for details.
