### ISSUE TITLE
Support CSS-like styling and layout

### ISSUE THREAD

**Issue by teratorn** [andlabs/libui#370] opened 2018-05-22 04:30 UTC
It would help transition people with UI dev experience using stylesheets to support something like CSS something like how Qt does it

**Comment by andlabs** [comment] 2018-05-22 05:13
This would require implementing a CSS parser on Windows and macOS, as well as a CSS layout parser on GTK+, as layout is still done outside of CSS there.

That being said, duplicate of #313

**Closed by andlabs** 2018-05-22 05:13 UTC
